#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
gen-mcp-config.py — 生成 / 安装 DSH MCP 插件配置（mcp-client）。

DSH 的 MCP 桥接（@deepseek-ai/dsh-mcp-client）以 cordis 插件行存在，
每个 mcp-client 实例连接一个 stdio MCP server，工具注册为
mcp__<serverName>__<rawName>。插件行合并进活动 profile 的
cordis.patch.yml（$DSH_HOME/profiles/<name>/cordis.patch.yml）。

用法:
  python android_mcp\\scripts\\gen-mcp-config.py                  # 只生成 generated/cordis.mcp.patch.yml
  python android_mcp\\scripts\\gen-mcp-config.py --profile web    # 生成并合并到 web profile（自动备份）
  python android_mcp\\scripts\\gen-mcp-config.py --profile web --dry-run   # 预演，不写 profile
  python android_mcp\\scripts\\gen-mcp-config.py --profile web --uninstall  # 从 profile 移除本包生成的条目

环境变量:
  DSH_HOME 覆盖 dsh home（默认 %USERPROFILE%\.dsh）
  ANDROID_MCP_PYTHON 指定 python 解释器（默认 sys.executable）
"""

import argparse
import os
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("[gen-mcp-config] 缺少 pyyaml: pip install pyyaml")

ROOT = Path(__file__).resolve().parents[2]          # android_mcp/scripts -> android_mcp -> 项目根
DEFAULT_OUT = ROOT / "android_mcp" / "mcp" / "generated" / "cordis.mcp.patch.yml"

SERVERS = [
    {
        "id": "mcp-reverse-index",
        "serverName": "reverse_index",
        "serverType": "reverse_index",
        "env": {},
        "note": "jadx/apktool 反编译产物索引与检索（阶段2 静态分析）",
    },
    {
        "id": "mcp-frida-orchestrator",
        "serverName": "frida_orchestrator",
        "serverType": "frida_orchestrator",
        "env": {
            "ANDROID_MCP_ALLOW_EMULATOR": "0",
            "ANDROID_MCP_FRIDA_DEVICE": "9C181EC3BF7E0D",
            "ANDROID_MCP_REMOTE_PATCHED_FRIDA": "/data/local/tmp/florida-server",
        },
        "note": "ADB/Root/Frida 编排、算法助手/LSPosed/HMA 非 UI 操作、frida_rpc_call",
    },
    {
        "id": "mcp-algo-lab",
        "serverName": "algo_lab",
        "serverType": "algo_lab",
        "env": {},
        "note": "编码识别、Hash/HMAC 候选验证、python 复现器",
    },
    {
        "id": "mcp-charles",
        "serverName": "charles",
        "serverType": "charles",
        "env": {},
        "note": "Charles Proxy Web Interface 会话读取（需 Charles GUI 开启 8888）",
    },
    {
        "id": "mcp-unidbg",
        "serverName": "unidbg",
        "serverType": "unidbg",
        "env": {},
        "note": "unidbg 离线 SO 参数生成（JPype 进程内调 jar）；需 UNIDBG_JAVA_HOME 指向 JDK8（0.9.9 老框架）",
    },
]

PATCH_HEADER = """# DSH MCP servers (generated by android_mcp\\scripts\\gen-mcp-config.py — do not edit by hand)
# 每个条目是一个 @deepseek-ai/dsh-mcp-client 插件实例，连接一个 stdio MCP server。
# 工具注册名: mcp__<serverName>__<rawName>。删除本段可整体卸载。
"""


def bridge_args(root: Path, server_type: str) -> list:
    # YAML 双引号字符串里 \\ 是转义后的单个 \；这里给 python 的值就是原始反斜杠路径，
    # safe_dump 会自动处理转义。
    return [str(root / "android_mcp" / "mcp-bridge.py"), server_type]


def build_entries(root: Path, python: str) -> list:
    entries = []
    for s in SERVERS:
        entries.append({
            "id": s["id"],
            "name": "@deepseek-ai/dsh-mcp-client",
            "config": {
                "transport": "stdio",
                "serverName": s["serverName"],
                "command": python,
                "args": bridge_args(root, s["serverType"]),
                "cwd": str(root),
                "env": s["env"] or {},
                "toolCallTimeoutMs": 120000,
            },
        })
    return entries


def profile_patch_path(dsh_home: Path, profile: str) -> Path:
    return dsh_home / "profiles" / profile / "cordis.patch.yml"


def load_patch(path: Path) -> list:
    if not path.exists():
        return []
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as e:
        sys.exit(f"[gen-mcp-config] 解析 {path} 失败: {e}")
    return data if isinstance(data, list) else []


def merge_entries(patch: list, entries: list) -> list:
    ids = {e.get("id") for e in patch}
    added = 0
    for e in entries:
        if e.get("id") in ids:
            continue
        patch.append(e)
        ids.add(e.get("id"))
        added += 1
    return patch, added


def remove_entries(patch: list, ids: set) -> list:
    kept = [e for e in patch if e.get("id") not in ids]
    return kept, len(patch) - len(kept)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate/install DSH MCP client config")
    ap.add_argument("--root", default=str(ROOT), help="project root (auto-detected)")
    ap.add_argument("--python", default=os.environ.get("ANDROID_MCP_PYTHON", sys.executable),
                    help="python interpreter for MCP servers")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output patch yml path")
    ap.add_argument("--profile", default=None, help="profile name to merge into (e.g. web)")
    ap.add_argument("--dry-run", action="store_true", help="do not write the profile patch")
    ap.add_argument("--uninstall", action="store_true", help="remove generated entries from the profile patch")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    python = args.python
    if not (root / "android_mcp" / "mcp-bridge.py").exists():
        sys.exit(f"[gen-mcp-config] 找不到 {root / 'android_mcp' / 'mcp-bridge.py'}")

    entries = build_entries(root, python)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(entries, allow_unicode=True, sort_keys=False, width=200)
    out.write_text(PATCH_HEADER + body, encoding="utf-8")
    print(f"[gen-mcp-config] 已生成 {out}（{len(entries)} 个 mcp-client 实例）")

    if not args.profile:
        return 0

    dsh_home = Path(os.environ.get("DSH_HOME", str(Path.home() / ".dsh")))
    patch_path = profile_patch_path(dsh_home, args.profile)
    print(f"[gen-mcp-config] profile patch: {patch_path}")

    if args.uninstall:
        if not patch_path.exists():
            print("[gen-mcp-config] profile patch 不存在，无需卸载")
            return 0
        patch = load_patch(patch_path)
        ids = {e["id"] for e in entries}
        kept, removed = remove_entries(patch, ids)
        if removed == 0:
            print("[gen-mcp-config] 未发现本包生成的条目")
            return 0
        if args.dry_run:
            print(f"[gen-mcp-config] [dry-run] 将移除 {removed} 条")
            return 0
        shutil.copy2(patch_path, str(patch_path) + ".bak")
        patch_path.write_text(yaml.safe_dump(kept, allow_unicode=True, sort_keys=False), encoding="utf-8")
        print(f"[gen-mcp-config] 已移除 {removed} 条，备份 {patch_path}.bak")
        return 0

    patch = load_patch(patch_path)
    merged, added = merge_entries(patch, entries)
    print(f"[gen-mcp-config] profile 现有 {len(patch)} 条，本次新增 {added} 条"
          + ("（id 冲突已跳过）" if added < len(entries) else ""))
    if args.dry_run:
        print("[gen-mcp-config] [dry-run] 未写 profile；重启 DSH 后生效")
        return 0
    if not patch_path.exists():
        patch_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        shutil.copy2(patch_path, str(patch_path) + ".bak")
    patch_path.write_text(yaml.safe_dump(merged, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"[gen-mcp-config] 已合并到 {patch_path}（备份 {patch_path}.bak）")
    print("[gen-mcp-config] 重启 DSH（或重载插件）后，MCP 工具将以 mcp__<serverName>__<tool> 出现")
    return 0


if __name__ == "__main__":
    sys.exit(main())
